spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
  thymeleaf:
    cache: false
security:
  ignored: /login.html
server:
  context-path: /shop


