spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 6789@jkl
  thymeleaf:
    cache: false
server:
  context-path: /findjob
  error:
    whitelabel:
      enabled: false
  port: 8081
  ssl:
    enabled: true
    key-alias: tomcat
    key-password: tomcat
    key-store: classpath:keystore/tomcat.keystore
management:
  security:
    enabled: false
security:
  basic:
    realm: ${random.value}





